### ISSUE TITLE
Compass not compiling sass 

### ISSUE THREAD

**Issue by humanaut** [guard/guard-compass#16]
Hello. 

I have installed guard and guard compass and followed the instructions. 

All my project files are in one folder. 

After typing guard in my terminal it doesn't throw any errors except a deprecated regex pattern. 

My simple sass file doesn't compile. No messages other telling me it's active and watching the directories / files. 

I have included the required lines of code in my gem file and my guard file. I also have a config.rb file. 

Am I missing any dependencies perhaps, or do I need to use guard sass still also or any order combinations? 

I previously had guard-sass working with guard-livereload but needed/wanted to take advantage of a config.rb file that I use from a drupal theme often,  so i assumed I needed to use guard compass instead. 

I can provide code example from files if requested. 

Thanks for any helpful in advance.

**Comment by oliamb** [comment]
Yeah, I don't use compass anymore for years. Someone should take over this lib, I will be more than happy to help for the transition. Anyone?

**Comment by netzpirat** [comment]
> I have installed guard and guard compass and followed the instructions.

It looks like guard-compass isn't maintained anymore, the instructions are outdated, e.g `compass -f blueprint my_compass_project` doesn't work anymore.

> All my project files are in one folder.

That should be no problem, Guard can be configured to almost any project structure.

> After typing guard in my terminal it doesn't throw any errors except a deprecated regex pattern.

The default configuration for guard-compass is

```
guard 'compass' do
  watch('^src/(.*)\.s[ac]ss')
end
```

which uses an outdated configuration. You need to supply a regex to get rid of the warning. Just
use

```
guard 'compass' do
  watch(%r{^src/(.*)\.s[ac]ss})
end
```

and make sure that `src` is the directory where your sass or scss files are located.

> My simple sass file doesn't compile. No messages other telling me it's active and watching the directories / files.

That usually means that the `watch` expression doesn't match your directory structure.

> I have included the required lines of code in my gem file and my guard file. I also have a config.rb file.

Can you shared those files, so we can have a look?

> Am I missing any dependencies perhaps, or do I need to use guard sass still also or any order combinations?

I'm not using guard-compass myself, but it looks that it doesn't have any special dependencies other than compass itself. No need to install guard-sass.

> I previously had guard-sass working with guard-livereload but needed/wanted to take advantage of a config.rb file that I use from a drupal theme often, so i assumed I needed to use guard compass instead.

Yes, it looks like guard-sass doesn't support a config.rb, but Joshua does a great job maintaining the Guard plugin. Since Oli doesn't maintain guard-compass, I'd stick with guard-sass and rather ask Joshua if he's interested in add support for the Compass `config.rb` configuration file.

**Comment by humanaut** [comment]
Looks like it's working now. I just had to have the correct folder specified for guard-compass to watch.

That being said, I might still check and see if guard-sass can do what I need it to do when it comes to the options within my config.rb file. 

Thanks again for the write up.
